language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git libtool autoconf automake
  - git clone git://github.com/bitcoin/secp256k1.git libsecp256k1
  - cd libsecp256k1
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - sudo bash -c 'echo /usr/local/lib > /etc/ld.so.conf.d/local.conf'
  - sudo ldconfig
  - sudo pip install cffi coverage coveralls -U
install:
  - python setup.py -q install
script: coverage run --source=secp256k1 setup.py pytest
after_success:
  - coveralls
