language: python
python:
  - "2.7"
  - "3.3"

sudo: false

addons:
  apt:
    packages:
      - git
      - libtool
      - autoconf
      - automake

before_install:
  - git clone git://github.com/bitcoin/secp256k1.git libsecp256k1
  - pushd libsecp256k1
  - ./autogen.sh
  - ./configure --enable-module-recovery --enable-module-ecdh --enable-module-schnorr
  - make
  - popd
  - virtualenv ENV
  - source ENV/bin/activate
  - pip install -U pip setuptools cffi coverage coveralls

install:
  - LIB_PATH=./libsecp256k1/.libs HEADER_PATH=./libsecp256k1/include python setup.py -q install

script:
  - LD_LIBRARY_PATH=./libsecp256k1/.libs coverage run --source=secp256k1 setup.py pytest

after_success:
  - coveralls
